### ISSUE TITLE
Version for PyQt5.14

### ISSUE THREAD

**Issue by filin86** [altendky/pyqt5-tools#40] opened 2020-01-31 07:32 UTC
Can you please create new version for recent version (5.14.1) PyQt5 and py 3.8?

**Comment by altendky** [comment] 2020-02-05 04:14
Sadly, I wouldn't hold my breath on this.  5.14 changed to SIP v5 and new build processes.  Rather than other versions for awhile where I've just added some new version numbers and relationships my understanding is that I will have to rework the build process.  I've wanted to switch over to Azure Pipelines (or maybe GitHub Actions), rework the build process, add support for Linux (and macOS?), etc etc so I'm going to have to try to find time to do all this now, I think.  I'm sorry I don't have better news.

While workarounds aren't what any of us want, sometimes they are useful.  If you aren't using custom widgets in Designer then you might be able to get away with a second env (https://bit.ly/py-env) that just holds pyqt5-tools and its corresponding PyQt5 version.  You'll still be able to open whatever .ui files etc.

**Comment by altendky** [comment] 2020-02-13 14:31
http://fstab.net/permanent/pyqt5_tools-5.14.1.1.6rc1.post118-py3-none-any.whl

I've got plenty more to do but at least designer is loading the pyqt plugin...  let me know if it works or what issues you have.

**Comment by filin86** [comment] 2020-02-13 16:35
You are a wonderful person! Thank you!
Your work helped me build a unified environment and simplify testing (custom widgets is my case).

Designer started and all my plugins loaded. I don't think there should be any problems

**Comment by altendky** [comment] 2020-02-13 18:00
Good deal. I'll keep this open until I get the other pieces working and it up on pypi.

**Comment by Hyperclaw79** [comment] 2020-04-14 12:39
> http://permanent.fstab.net/python/wheels/pyqt5_tools-5.14.1.1.6rc1.post118-py3-none-any.whl
@altendky Thank you very much for the wheel. Why not add this to pypi under the `--pre` flag which was intending for cutting edge versions?

**Comment by altendky** [comment] 2020-04-14 14:00
I keep imagining I'm closing to getting this batch of work done.  Also, it's been super unstable.  But, I think I've got Windows and Linux support 'stable' and being tested in CI so I could probably afford to offer them via PyPI as prerelease versions.  There's a chance I can get to that today.  I'll mention here if I do.

**Comment by altendky** [comment] 2020-04-16 12:16
Windows and Linux wheels are up as v5.14.2.1.7b2.  Let me know how they work.  I'm still working on macOS wheels and the Designer plugin doesn't have the exception dialog code patched into it presently.

https://pypi.org/project/pyqt5-tools/5.14.2.1.7b2/#files

**Comment by Hyperclaw79** [comment] 2020-04-16 13:03
Wow that's a good progress!
The unofficial one was working like a charm, does the pypi version have any breaking changes?
I will test it for the basic functionality and see if anything is off.
Thank you

**Comment by altendky** [comment] 2020-04-16 13:05
Other than the exception dialog...  I think it matches previous releases?  This was intended to be an effort to update the build process, not change how things worked.

**Comment by altendky** [comment] 2020-04-17 03:26
1.7b3 should have the exception dialog and all three of 5.14.0/1/2.  I haven't decided long term how many micro-versions I'll keep building for how long.

**Comment by altendky** [comment] 2020-06-14 12:01
I'm still straggling on getting macOS going but I just kicked out v1.7 with 5.14.0/1/2 and 5.15.0.

https://pypi.org/project/pyqt5-tools/#history

**Closed** 2020-07-11 15:25 UTC
